import {it,expect} from 'vitest';
import {previewIdentityHandler,expectedPreviewIdentity,safeIdentityFailure,safeDatabaseConfiguration} from './acquisition-preview-identity';
import type {BoundSql} from './acquisition-repository';
const forbidden:BoundSql={query:async()=>{throw Error('must not query');}};
it('identity is absent outside Preview before any database query',async()=>{for(const environment of [undefined,'production','development']){const r=await previewIdentityHandler(environment,forbidden)();expect(r.status).toBe(404);}});
it('returns only exact four approved identifiers and match result',async()=>{let query='';const sql:BoundSql={query:async<T>(s:string)=>{query=s;return [{...expectedPreviewIdentity,password:'SYNTHETIC-DO-NOT-RETURN',url:'SYNTHETIC-DO-NOT-RETURN'}] as T[];}};const r=await previewIdentityHandler('preview',sql)();expect(r.status).toBe(200);const body=await r.json();expect(body).toEqual({identity:expectedPreviewIdentity,matches:true,migrationBlocked:false});expect(query).not.toMatch(/User|Session|DATABASE_URL/);expect(r.headers.get('cache-control')).toBe('no-store');});
it('wrong, missing or unavailable provider metadata blocks migration',async()=>{for(const branchId of [null,'','br-billowing-sound-awdhj52d']){const sql:BoundSql={query:async<T>()=>[{...expectedPreviewIdentity,branchId}] as T[]};const r=await previewIdentityHandler('preview',sql)();expect(r.status).toBe(409);expect((await r.json()).migrationBlocked).toBe(true);}const r=await previewIdentityHandler('preview',forbidden)();expect(r.status).toBe(503);expect(await r.text()).not.toContain('must not query');});
it('allows only known error codes and never exception messages or arbitrary metadata',()=>{expect(safeIdentityFailure({code:'P1001',message:'SYNTHETIC-private-url',meta:{code:'08006',message:'SYNTHETIC-secret'}},'connection')).toEqual({stage:'connection',code:'P1001',sqlState:'08006',errorClass:'UNKNOWN'});expect(safeIdentityFailure({code:'SYNTHETIC-secret',meta:{code:'SYNTHETIC-secret'}},'provider-settings')).toEqual({stage:'provider-settings',code:'UNKNOWN',sqlState:null,errorClass:'UNKNOWN'});});
it('distinguishes connection failure from provider-settings failure without leaking data',async()=>{for(const failAfter of [0,1]){let calls=0;const sql:BoundSql={query:async<T>()=>{if(calls++===failAfter)throw {code:'P2010',meta:{code:'42501'},message:'SYNTHETIC-private-url'};return [{database:'neondb'}] as T[];}};const r=await previewIdentityHandler('preview',sql)();expect(r.status).toBe(503);const result=await r.json();expect(result.diagnostic).toEqual({stage:failAfter?'provider-settings':'connection',code:'P2010',sqlState:'42501',errorClass:'UNKNOWN'});expect(JSON.stringify(result)).not.toContain('SYNTHETIC-private-url');expect(result.migrationBlocked).toBe(true);}});

it('reads Prisma initialization errorCode instead of losing it as UNKNOWN',async()=>{const {Prisma}=await import('@prisma/client');const e=new Prisma.PrismaClientInitializationError('SYNTHETIC-private-message','6.19.3','P1001');expect(safeIdentityFailure(e,'connection')).toEqual({stage:'connection',code:'P1001',sqlState:null,errorClass:'PrismaClientInitializationError'});});
it('configuration summary contains only booleans, no connection values',()=>{const value='postgresql://SYNTHETIC-user:SYNTHETIC-private@SYNTHETIC-host/SYNTHETIC-db?sslmode=require';const c=safeDatabaseConfiguration(value);expect(c.formatValid).toBe(true);expect(Object.values(c).every(x=>typeof x==='boolean')).toBe(true);expect(JSON.stringify(c)).not.toContain('SYNTHETIC');for(const v of [undefined,'',"'"+value+"'",value+'\n','https://example/db','postgresql://example/'])expect(safeDatabaseConfiguration(v).formatValid).toBe(false);});
it('production never evaluates configuration and failures expose only safe categories',async()=>{let calls=0;expect((await previewIdentityHandler('production',forbidden,()=>{calls++;throw Error('must not run');})()).status).toBe(404);expect(calls).toBe(0);const r=await previewIdentityHandler('preview',forbidden,()=>safeDatabaseConfiguration(undefined))();const b=await r.json();expect(b.diagnostic.configuration.present).toBe(false);expect(JSON.stringify(b)).not.toContain('must not query');});
