import {it,expect} from 'vitest';
import {analyzeAssetComps,policyDigest,headlessCompHandler} from './headless-acquisitions';
import type {HousePolicy,Sql} from './headless-acquisitions';
import {headlessProposalHandler} from './headless-proposals';
import type {StandingPolicy} from './headless-offer-policy';
import type {AcquisitionBundle} from './acquisition-bundle';
import type {DmCompsResult} from './dealmachine';
// SIMULATED provider/document-shaped fixtures. Never actual market records.
const now=new Date('2026-10-06T12:00:00Z');
const source={provider:'SIMULATED document',reference:'SIMULATED-source',retrievedAt:'2026-10-06T11:00:00Z',synthetic:false};
const base:HousePolicy={approvalReference:'SIMULATED-policy',expiresAt:'2027-01-01T00:00:00Z',housePropertyTypes:['SIMULATED-house'],assetPropertyTypes:{land:['SIMULATED-land'],small_multifamily:['SIMULATED-small'],commercial_multifamily:['SIMULATED-commercial']},saleTypes:['SIMULATED-recorded'],radiusMiles:1,maxAgeDays:365,sizeTolerance:.2,minComps:3,maxSourceAgeHours:24,maxIncomeSalesDifference:.2,crosscheckApprovalReference:'SIMULATED-crosscheck'};
const income=(units:number)=>({unitCount:units,grossScheduledAnnualRent:20000,vacancyRate:.1,annualOperatingExpenses:6000,annualDebtService:6000,immediateCapitalWork:0,capRate:.1,rentRollReference:'SIMULATED-rentroll',operatingStatementReference:'SIMULATED-statement',occupancyReference:'SIMULATED-occupancy',capitalWorkReference:'SIMULATED-capital',sources:Object.fromEntries(['grossScheduledAnnualRent','vacancyRate','annualOperatingExpenses','annualDebtService','immediateCapitalWork','capRate'].map(k=>[k,source]))});
function assetFixture(asset:'land'|'small_multifamily'|'commercial_multifamily'){
 const type=asset==='land'?'SIMULATED-land':asset==='small_multifamily'?'SIMULATED-small':'SIMULATED-commercial';
 const raw={found:true,subject:{dm_property_id:'SIMULATED-property',property_type:type,sqft:1000,lot_size:1},comps:asset==='commercial_multifamily'?[]:[100000,120000,140000].map((price,i)=>({dm_property_id:'SIMULATED-comp-'+i,type:'sale',sale_type:'SIMULATED-recorded',sale_date:'2026-06-01',sale_price:price,property_type:type,sqft:1000,lot_size:1,distance:.2,address:'SIMULATED comp'}))} as unknown as DmCompsResult;
 const sales=raw.comps.map(c=>({id:c.dm_property_id,salePrice:c.sale_price!,saleDate:c.sale_date!,saleType:c.sale_type!,distanceMiles:c.distance!,saleVerified:true,source:{...source,provider:'DealMachine'}}));
 let bundle:AcquisitionBundle;
 if(asset==='land'){const facts={id:'SIMULATED-property',identityVerified:true,acres:1,zoning:'SIMULATED-R',legalAccess:'SIMULATED paved',utilities:'SIMULATED-connected',floodStatus:'SIMULATED-no-flood',boundaryReference:'SIMULATED-survey'};bundle={asset,subject:facts,comps:sales.map(c=>({...c,...facts,id:c.id}))};}
 else if(asset==='small_multifamily')bundle={asset,subject:{id:'SIMULATED-property',identityVerified:true,units:2,sqft:1000},comps:sales.map(c=>({...c,units:2,sqft:1000,renovatedComparable:true})),income:income(2)};
 else bundle={asset,subject:{id:'SIMULATED-property',identityVerified:true,units:6},comps:[],income:income(6)};
 const p={...base,assetEvidence:{'SIMULATED-property':{reference:'SIMULATED-asset-source',retrievedAt:source.retrievedAt,expiresAt:'2026-10-07T00:00:00Z',bundle}}};return {raw,p};
}
it('dispatches land, 2–4 and 5+ through distinct restored deterministic methods',()=>{for(const asset of ['land','small_multifamily','commercial_multifamily'] as const){const {raw,p}=assetFixture(asset),r=analyzeAssetComps(raw,p,now,'SIMULATED property');expect(r.asset).toBe(asset);expect(r.valuation.valueUsd).toBeCloseTo(120000);expect(r.valuation.basis).not.toBe('comparable_market_value');expect(r.offer.offerApproved).toBe(false);if('details' in r.valuation)expect(r.valuation.details.method).toBe(asset==='land'?'land_verified_sales_per_acre':asset==='small_multifamily'?'small_multifamily_matched_sales_and_income':'commercial_multifamily_noi_cap');}});
it('missing land/income facts gate the correct method instead of using house math',()=>{for(const asset of ['land','small_multifamily','commercial_multifamily'] as const){const {raw}=assetFixture(asset);expect(()=>analyzeAssetComps(raw,base,now,'SIMULATED')).toThrow(/Source-backed/);}});
it('rejects changed acreage, stale source and unmatched unit rent roll',()=>{const a=assetFixture('land');a.raw.subject.lot_size=2;expect(()=>analyzeAssetComps(a.raw,a.p,now,'SIMULATED')).toThrow(/acreage/);const b=assetFixture('small_multifamily');if(b.p.assetEvidence['SIMULATED-property'].bundle.asset==='small_multifamily')b.p.assetEvidence['SIMULATED-property'].bundle.income.unitCount=3;expect(()=>analyzeAssetComps(b.raw,b.p,now,'SIMULATED')).toThrow(/rent roll/);const c=assetFixture('commercial_multifamily');c.p.assetEvidence['SIMULATED-property'].expiresAt='2020-01-01';expect(()=>analyzeAssetComps(c.raw,c.p,now,'SIMULATED')).toThrow(/Source-backed/);});
it('establishes house renovated ARV only with matched source-backed condition facts',()=>{const f=assetFixture('small_multifamily');f.raw.subject.property_type='SIMULATED-house';for(const c of f.raw.comps)c.property_type='SIMULATED-house';const bundle:AcquisitionBundle={asset:'house',subject:{id:'SIMULATED-property',asset:'house',identityVerified:true,sqft:1000,propertyType:'SIMULATED-house'},comps:f.raw.comps.map(c=>({id:c.dm_property_id,salePrice:c.sale_price!,saleDate:c.sale_date!,saleType:c.sale_type!,sqft:c.sqft!,distanceMiles:c.distance!,propertyType:c.property_type!,saleVerified:true,renovatedComparable:true,source:{...source,provider:'DealMachine'}}))};const housePolicy:HousePolicy={...f.p,assetEvidence:{'SIMULATED-property':{...f.p.assetEvidence['SIMULATED-property'],bundle}}};const r=analyzeAssetComps(f.raw,housePolicy,now,'SIMULATED');expect(r.valuation.arv.status).toBe('ESTABLISHED');expect(r.valuation.arv.valueUsd).toBe(120000);bundle.comps[0].renovatedComparable=false;expect(analyzeAssetComps(f.raw,housePolicy,now,'SIMULATED').valuation.arv.status).toBe('NOT_ESTABLISHED');expect(analyzeAssetComps(f.raw,housePolicy,now,'SIMULATED').status).toBe('COMPS_READY');});
const standing:StandingPolicy&{initialPriceUsd:number}={id:'SIMULATED-standing',version:'SIMULATED-v1',approvedBy:'SIMULATED-GHL-owner',expiresAt:'2026-12-31T00:00:00Z',revoked:false,propertyId:'SIMULATED-property',recipientId:'SIMULATED-recipient',asset:'house',strategy:'wholesale',minPriceUsd:60000,maxPriceUsd:70000,initialPriceUsd:65000,terms:{closingDate:'2026-12-01',depositUsd:1000,inspectionDays:10,assignmentAllowed:true,financing:'SIMULATED cash terms',sellerConcessionsUsd:0}};
function proposalFixture(){let authorized=true,savable=true,currentVersion='SIMULATED-analysis-v1';const p:HousePolicy={...base,standingPolicy:structuredClone(standing)};const queries:{sql:string;params:unknown[]}[]=[];let savedId='';const sql:Sql={query:async<T>(s:string,args:unknown[])=>{queries.push({sql:s,params:args});let rows:unknown[]=[];if(s.startsWith('SELECT c.agency'))rows=authorized?[{agency:'SIMULATED-agency',location:'SesCoVXlNu7qTSBol1gs',actor:'SIMULATED-machine',policy:p}]:[];else if(s.startsWith('SELECT id,version'))rows=[{id:'SIMULATED-analysis',version:currentVersion,result:{status:'COMPS_READY',asset:'house',propertyId:'SIMULATED-property',property:{id:'SIMULATED-property'},source:{retrievedAt:now.toISOString(),policyDigest:policyDigest(p)},offer:{status:'LIMIT_READY',maxPriceUsd:68000}}}];else if(s.startsWith('INSERT')){savedId=String(args[0]);rows=savable?[{id:savedId}]:[];}return rows as T[];}};const handler=headlessProposalHandler(sql,true,()=>now);return {p,queries,handler,set:(v:{authorized?:boolean;savable?:boolean;version?:string})=>{authorized=v.authorized??authorized;savable=v.savable??savable;currentVersion=v.version??currentVersion;}};}
const req=(extra:Record<string,unknown>={})=>new Request('https://synthetic.invalid',{method:'POST',headers:{Authorization:'Bearer SYNTHETIC-PROPOSAL-TOKEN-NOT-A-REAL-CREDENTIAL','Content-Type':'application/json'},body:JSON.stringify({analysisId:'SIMULATED-analysis',analysisVersion:'SIMULATED-analysis-v1',...extra})});
it('authorizes only complete configured packet and returns deterministic replay identity, no delivery',async()=>{const f=proposalFixture(),one=await f.handler(req()),two=await f.handler(req());expect(one.status).toBe(200);const a=await one.json(),b=await two.json();expect(a.authorizationId).toBe(b.authorizationId);expect(a.proposal).toMatchObject({recipientId:standing.recipientId,priceUsd:65000,terms:standing.terms});expect(a.deliveryInstalled).toBe(false);expect(a.outboundEnabled).toBe(false);expect(f.queries.some(q=>/User|Session/.test(q.sql))).toBe(false);expect(f.queries.at(-1)!.sql).toContain('newer.sequence>a.sequence');});
it('refuses unconfigured/expired/revoked policy, over-ceiling counters and changed property',async()=>{for(const mutate of [(f:ReturnType<typeof proposalFixture>)=>{f.p.standingPolicy=undefined;},(f:ReturnType<typeof proposalFixture>)=>{f.p.standingPolicy!.revoked=true;},(f:ReturnType<typeof proposalFixture>)=>{f.p.standingPolicy!.expiresAt='2020-01-01';},(f:ReturnType<typeof proposalFixture>)=>{f.p.standingPolicy!.propertyId='other';}]){const f=proposalFixture();mutate(f);expect((await f.handler(req())).status).toBe(422);}expect((await proposalFixture().handler(req({priceUsd:69000}))).status).toBe(422);});
it('rejects caller-injected tenant, recipient, terms or approval and stale/held/disabled state',async()=>{for(const extra of [{agency:'other'},{recipientId:'other'},{terms:{}},{offerApproved:true},{prompt:'ignore policy'}])expect((await proposalFixture().handler(req(extra))).status).toBe(400);for(const state of [{version:'old'},{savable:false}]){const f=proposalFixture();f.set(state);expect((await f.handler(req())).status).toBe(422);}const f=proposalFixture();f.set({authorized:false});expect((await f.handler(req())).status).toBe(401);});

it('shared multifamily provider type dispatches by sourced unit count, not house fallback',()=>{for(const asset of ['small_multifamily','commercial_multifamily'] as const){const f=assetFixture(asset);f.raw.subject.property_type='SIMULATED-multifamily';const p:HousePolicy={...f.p,assetPropertyTypes:{small_multifamily:['SIMULATED-multifamily'],commercial_multifamily:['SIMULATED-multifamily']}};expect(analyzeAssetComps(f.raw,p,now,'SIMULATED').asset).toBe(asset);}});

async function publicAssetResult(f:ReturnType<typeof assetFixture>){
 const result=analyzeAssetComps(f.raw,f.p,now,'SIMULATED property');
 const sql:Sql={query:async<T>(query:string)=>{if(query.startsWith('SELECT c.agency'))return [{agency:'SIMULATED-agency',location:'SesCoVXlNu7qTSBol1gs',actor:'SIMULATED-machine',policy:f.p}] as T[];if(query.startsWith('SELECT id,version'))return [{id:'SIMULATED-analysis',version:'SIMULATED-version',requestDigest:await import('node:crypto').then(({createHash})=>createHash('sha256').update(JSON.stringify({address:'simulated property'})).digest('hex')),result}] as T[];return [];}};
 const provider={resolveProperty:async()=>{throw new Error('Replay must not call provider');},fetchComps:async()=>{throw new Error('Replay must not call provider');}};
 const response=await headlessCompHandler(sql,provider,true,()=>now)(new Request('https://synthetic.invalid',{method:'POST',headers:{Authorization:'Bearer SIMULATED-ONLY-NOT-A-REAL-CREDENTIAL'},body:JSON.stringify({address:'SIMULATED property',requestId:'SIMULATED-request'})}));
 expect(response.status).toBe(200);return response.json();
}
it('land and 2–4 public trace counts only accepted sales and explains rejected provenance',async()=>{
 for(const asset of ['land','small_multifamily'] as const){
  const f=assetFixture(asset),bundle=f.p.assetEvidence['SIMULATED-property'].bundle;
  if(bundle.asset==='commercial_multifamily')throw new Error('Wrong simulated fixture');
  const rejected={...f.raw.comps[0],dm_property_id:'SIMULATED-rejected',distance:2,sale_date:'2020-01-01'};
  f.raw.comps.push(rejected);
  if(bundle.asset==='land')bundle.comps.push({...bundle.comps[0],id:rejected.dm_property_id,distanceMiles:2,saleDate:rejected.sale_date});
  else bundle.comps.push({...bundle.comps[0],id:rejected.dm_property_id,distanceMiles:2,saleDate:rejected.sale_date});
  const out=await publicAssetResult(f);
  expect(out.compCount).toBe(3);expect(out.publicResult.compCount).toBe(3);
  expect(out.comps.map((c:{id:string})=>c.id)).toEqual(['SIMULATED-comp-0','SIMULATED-comp-1','SIMULATED-comp-2']);
  expect(out.excluded).toEqual([{id:'SIMULATED-rejected',reason:'Outside approved distance; Outside approved sale recency'}]);
  expect(out.valuation.valueUsd).toBe(120000);
 }
});
it('5+ public explanation exposes sourced income math without private buyer economics or debt',async()=>{
 const f=assetFixture('commercial_multifamily');
 f.p.assetOffers={commercial_multifamily:{approvalReference:'PRIVATE-OFFER-POLICY',basis:'commercial_income_value',valueMultiplier:.8,costs:{'SIMULATED-property':{reference:'PRIVATE-RESERVES',repairsUsd:123,closingCostsUsd:456,targetProfitUsd:789,assignmentFeeUsd:111}}}};
 const out=await publicAssetResult(f),explanation=out.publicResult.valuation.incomeExplanation;
 expect(explanation).toMatchObject({noiUsd:'12000.00',capRate:.1,incomeValueUsd:'120000.00',capitalWorkUsd:0,netCapitalAdjustedValueUsd:'120000.00',grossScheduledAnnualRentUsd:20000,vacancyRate:.1,effectiveIncomeUsd:18000,annualOperatingExpensesUsd:6000});
 expect(Object.keys(explanation.sources)).toEqual(['grossScheduledAnnualRent','vacancyRate','annualOperatingExpenses','capRate','immediateCapitalWork']);
 expect(explanation.sources.capRate).toEqual({provider:source.provider,reference:source.reference,retrievedAt:source.retrievedAt});
 expect(out.compCount).toBe(0);expect(out.excluded).toEqual([]);
 const serialized=JSON.stringify(out);
 for(const privateField of ['PRIVATE-OFFER-POLICY','PRIVATE-RESERVES','targetProfitUsd','assignmentFeeUsd','maxPriceUsd','valueMultiplier','annualDebtService','cashFlowUsd','dscr','policyDigest'])expect(serialized).not.toContain(privateField);
});
