import {it,expect,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {headlessNativeQuoteHandler,QUOTE_RESPONSE_BUDGET_MS} from './headless-native-quote';
import {CALCULATOR_VERSION,type FinalizeQuote,type NativeQuoteRuntime,type QuoteReceipt,type QuoteSnapshot} from './native-quote-contract';
import {LOCATION} from './native/contracts';
import {quoteTestFixture,TEST_NOW} from './native-quote.test-fixtures';
import type {Sql} from './headless-acquisitions';

const token='TEST_ONLY-machine-token-not-a-credential';
const principal={agency:'TEST_ONLY-agency',location:LOCATION,actor:'TEST_ONLY-machine',policy:{legacy:'ignored'}};
function auth(){const query=vi.fn(async()=>[principal]);return {sql:{query} as unknown as Sql,query};}
function req(body:unknown,headers:Record<string,string>={}){return new Request('https://example.invalid/api/acquisitions/quote',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...headers},body:JSON.stringify(body)});}
function receipt(x:FinalizeQuote):QuoteReceipt{return {quoteId:'TEST_ONLY-native-quote',...x.principal,location:LOCATION,requestId:x.request.request_id,requestDigest:x.requestDigest,decisionDigest:x.decisionDigest,callId:x.request.call_id,contactId:x.request.contact_id,propertyRecordId:x.request.property_record_id,analysisRecordId:x.request.analysis_id,analysisVersion:x.request.analysis_version,nativeRevision:x.expectedNativeRevision,offerAmountUsd:x.offerAmountUsd,expiresAt:x.expiresAt,calculatorVersion:x.calculatorVersion,authorizationReference:'TEST_ONLY-authorization',durableReadbackReference:'TEST_ONLY-readback'};}
/** Protocol test double only. A shared map does NOT prove native storage or distributed atomicity. */
function runtime(snapshot:QuoteSnapshot){const ledger=new Map<string,QuoteReceipt>();return {loadSnapshot:vi.fn(async()=>structuredClone(snapshot)),finalizeQuote:vi.fn(async(x:FinalizeQuote)=>{const key=JSON.stringify([x.principal,x.request.request_id]),prior=ledger.get(key);if(prior)return prior.requestDigest===x.requestDigest&&prior.decisionDigest===x.decisionDigest?{state:'REPLAY',receipt:prior}:{state:'CONFLICT'};const r=receipt(x);ledger.set(key,r);return {state:'COMMITTED',receipt:r};})};}
function setup(){const f=quoteTestFixture(),a=auth(),native=runtime(f.snapshot);const handler=headlessNativeQuoteHandler(a.sql,native,true,()=>new Date(TEST_NOW));return {...f,...a,native,handler};}
async function result(response:Response){const body=await response.json();expect(response.headers.get('cache-control')).toBe('no-store');expect(Object.keys(body).sort()).toEqual((body.status==='QUOTE_READY'?['status','quote_id','currency','speak_text','calculator_version','offer_amount']:['status','quote_id','currency','speak_text','calculator_version']).sort());return body;}
function testComps(snapshot:QuoteSnapshot){return snapshot.observed.pair.compsProjection as {data:{comps:{sale_price:unknown;sale_type:string}[]}[]};}
it('returns only the exact eligible estimated offer, not ARV, repairs, ceilings or provider data',async()=>{const x=setup(),response=await x.handler(req(x.request)),body=await result(response);expect(response.status).toBe(200);expect(body).toMatchObject({status:'QUOTE_READY',quote_id:'TEST_ONLY-native-quote',currency:'USD',offer_amount:x.amount,calculator_version:CALCULATOR_VERSION});expect(body.speak_text).toContain('preliminary property and repair estimates');expect(x.query).toHaveBeenCalledTimes(3);for(const [sql,args] of x.query.mock.calls as unknown as [string,unknown[]][]){expect(sql).toContain('m.role=\'analysis_machine\'');expect(sql).toContain('s.selected=TRUE');expect(args).toEqual([createHash('sha256').update(token).digest('hex'),LOCATION,['acquisitions:analyze','acquisitions:propose']]);expect(JSON.stringify(args)).not.toContain(token);}});
it('keeps disabled and unbound production runtimes unavailable',async()=>{const x=setup();for(const [enabled,native] of [[false,x.native],[true,null]] as const){const response=await headlessNativeQuoteHandler(x.sql,native,enabled)(req(x.request));expect(response.status).toBe(503);expect(await result(response)).toMatchObject({status:'UNAVAILABLE'});}expect(x.native.loadSnapshot).not.toHaveBeenCalled();});
it.each(['','Bearer short','Bearer '+token+' whitespace','bearer '+token])('rejects invalid authentication %s before native reads',async authorization=>{const x=setup(),response=await x.handler(req(x.request,{authorization}));expect(response.status).toBe(401);expect((await result(response)).status).toBe('UNAUTHORIZED');expect(x.native.loadSnapshot).not.toHaveBeenCalled();});
it('rejects missing, duplicate and foreign-location machine principals',async()=>{for(const rows of [[],[principal,principal],[{...principal,location:'OTHER'}]]){const x=setup();x.query.mockResolvedValue(rows as typeof principal[]);expect((await result(await x.handler(req(x.request)))).status).toBe('UNAUTHORIZED');expect(x.native.loadSnapshot).not.toHaveBeenCalled();}});
it.each(['missing-analysis','foreign-location','address','price','policy','extra','oversized','bad-json','bad-type'])('rejects caller-supplied or malformed input: %s',async kind=>{const x=setup(),body:Record<string,unknown>={...x.request};if(kind==='missing-analysis')delete body.analysis_id;if(kind==='foreign-location')body.location_id='OTHER';if(kind==='address')body.address='some address';if(kind==='price')body.offer_amount=1;if(kind==='policy')body.policy={approved:true};if(kind==='extra')body.nativeSnapshot=x.snapshot;if(kind==='oversized')body.request_id='x'.repeat(9000);const request=kind==='bad-json'?new Request('https://example.invalid',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:'{bad'}):req(body,kind==='bad-type'?{'content-type':'text/plain'}:{});const response=await x.handler(request);expect(response.status).toBe(400);expect((await result(response)).status).toBe('INVALID_REQUEST');expect(x.native.loadSnapshot).not.toHaveBeenCalled();});
it('missing native snapshot never releases an amount',async()=>{const x=setup();const native:NativeQuoteRuntime={...x.native,loadSnapshot:async()=>null};expect((await result(await headlessNativeQuoteHandler(x.sql,native,true)(req(x.request)))).status).toBe('MISSING_INPUT');expect(native.finalizeQuote).not.toHaveBeenCalled();});
it.each(['proposed','revoked-policy','wrong-policy-approver','wrong-call','second-property','wrong-analysis','stale','incomplete','untrusted-unit','malformed-price','unknown-price','opening-amount','changed-terms','missing-authority','old-repair-rates'])('blocks unready native input: %s',async kind=>{const x=setup(),s=x.snapshot;if(s.observed.operation!=='reconcile')throw Error('fixture');if(kind==='proposed')s.compPolicyAdoption.status='PROPOSED';if(kind==='revoked-policy')s.compPolicyAdoption.revoked=true;if(kind==='wrong-policy-approver')s.compPolicyAdoption.approvedBy='OTHER';if(kind==='wrong-call')s.callBinding.callId='OTHER';if(kind==='second-property')s.callBinding.propertyRecordId='TEST_ONLY-property-two';if(kind==='wrong-analysis')s.observed.bound.context.property.currentAnalysisId='OTHER';if(kind==='stale')s.callBinding.expiresAt=TEST_NOW;if(kind==='incomplete')s.observed.readback.analysis.properties.completion_state='PENDING';if(kind==='untrusted-unit')s.observed.bound.bindings.currency.reference='';if(kind==='malformed-price')testComps(s).data[0].comps[0].sale_price='malformed';if(kind==='unknown-price')testComps(s).data[0].comps[0].sale_type='unknown';if(kind==='opening-amount')s.offer.packet.priceUsd+=1;if(kind==='changed-terms')s.offer.packet.terms.depositUsd+=1;if(kind==='missing-authority')s.offer.standing.approvalReference='';if(kind==='old-repair-rates')s.wholesale.policy.repairModelVersion='house-screening-2026-10-07-v1';x.native.loadSnapshot.mockResolvedValue(s);expect((await result(await x.handler(req(x.request)))).status).not.toBe('QUOTE_READY');expect(x.native.finalizeQuote).not.toHaveBeenCalled();});
it.each(['stop','takeover','property-hold','fresh-readback-stop','fresh-readback-takeover'])('preserves %s without an amount',async kind=>{const x=setup(),s=x.snapshot;if(s.observed.operation!=='reconcile')throw Error('fixture');const c=s.observed.bound.context;if(kind==='stop')c.contactDnd=true;if(kind==='takeover')c.contactTakeover=true;if(kind==='property-hold')c.property.held='true';if(kind==='fresh-readback-stop')s.observed.readback.contact.contactDnd=true;if(kind==='fresh-readback-takeover')s.observed.readback.contact.contactTakeover=true;x.native.loadSnapshot.mockResolvedValue(s);expect((await result(await x.handler(req(x.request)))).status).toBe('HELD');expect(x.native.finalizeQuote).not.toHaveBeenCalled();});
it('replays the same durable protocol receipt across fresh handler instances',async()=>{const x=setup(),first=await result(await x.handler(req(x.request)));const next=headlessNativeQuoteHandler(x.sql,x.native,true,()=>new Date(TEST_NOW));expect(await result(await next(req(x.request)))).toEqual(first);expect(x.native.finalizeQuote).toHaveBeenCalledTimes(2);});
it('conflicts when the same request ID refers to a changed native decision',async()=>{const x=setup();expect((await result(await x.handler(req(x.request)))).status).toBe('QUOTE_READY');x.snapshot.revision='TEST_ONLY-revision-two';x.native.loadSnapshot.mockResolvedValue(x.snapshot);const response=await x.handler(req(x.request));expect(response.status).toBe(409);expect((await result(response)).status).toBe('REPLAY_CONFLICT');});
it('does not replay a prior quote after a fresh STOP',async()=>{const x=setup();await x.handler(req(x.request));if(x.snapshot.observed.operation!=='reconcile')throw Error('fixture');x.snapshot.observed.readback.contact.contactDnd=true;x.native.loadSnapshot.mockResolvedValue(x.snapshot);expect((await result(await x.handler(req(x.request)))).status).toBe('HELD');expect(x.native.finalizeQuote).toHaveBeenCalledTimes(1);});
it.each([['HELD','HELD'],['STATE_CHANGED','NEEDS_REVIEW'],['IN_PROGRESS','IN_PROGRESS'],['UNAVAILABLE','UNAVAILABLE'],['CONFLICT','REPLAY_CONFLICT']])('never exposes an amount when final atomic comparison returns %s',async(state,status)=>{const x=setup(),native:NativeQuoteRuntime={...x.native,finalizeQuote:async()=>({state})};expect((await result(await headlessNativeQuoteHandler(x.sql,native,true,()=>new Date(TEST_NOW))(req(x.request)))).status).toBe(status);});
it.each(['agency','actor','contactId','propertyRecordId','analysisRecordId','analysisVersion','requestDigest','decisionDigest','nativeRevision','offerAmountUsd','expiresAt','calculatorVersion','authorizationReference','durableReadbackReference'])('refuses a mismatched or incomplete authorization receipt: %s',async key=>{const x=setup(),native:NativeQuoteRuntime={...x.native,finalizeQuote:async input=>{const r:Record<string,unknown>=receipt(input);r[key]=key==='offerAmountUsd'?input.offerAmountUsd+1:key==='expiresAt'?TEST_NOW:key.endsWith('Digest')?'f'.repeat(64):key.endsWith('Reference')?'':'OTHER';return {state:'COMMITTED',receipt:r};}};expect((await result(await headlessNativeQuoteHandler(x.sql,native,true,()=>new Date(TEST_NOW))(req(x.request)))).status).not.toBe('QUOTE_READY');});
it.each([2,3])('refuses revoked authority at authentication check %s',async check=>{const x=setup();x.query.mockImplementation(async()=>x.query.mock.calls.length===check?[]:[principal]);expect((await result(await x.handler(req(x.request)))).status).toBe('UNAUTHORIZED');expect(x.native.finalizeQuote).toHaveBeenCalledTimes(check===2?0:1);});
it('contains runtime errors without exposing payloads',async()=>{const x=setup();x.native.loadSnapshot.mockRejectedValue(Error('PRIVATE_MARKER'));const response=await x.handler(req(x.request)),body=await result(response);expect(body.status).toBe('UNAVAILABLE');expect(JSON.stringify(body)).not.toContain('PRIVATE_MARKER');});
it('bounds slow native reads and never starts finalization after timeout',async()=>{vi.useFakeTimers();try{const x=setup();let finish!:(s:QuoteSnapshot)=>void;const native:NativeQuoteRuntime={...x.native,loadSnapshot:()=>new Promise(resolve=>{finish=resolve;})};const pending=headlessNativeQuoteHandler(x.sql,native,true,()=>new Date(TEST_NOW))(req(x.request));await vi.advanceTimersByTimeAsync(QUOTE_RESPONSE_BUDGET_MS);expect((await result(await pending)).status).toBe('IN_PROGRESS');finish(x.snapshot);await vi.advanceTimersByTimeAsync(1);expect(native.finalizeQuote).not.toHaveBeenCalled();}finally{vi.useRealTimers();}});
it('times out uncertain finalization without an amount and signals cancellation',async()=>{vi.useFakeTimers();try{const x=setup();let input:FinalizeQuote|undefined;const native:NativeQuoteRuntime={...x.native,finalizeQuote:arg=>{input=arg;return new Promise(()=>undefined);}};const pending=headlessNativeQuoteHandler(x.sql,native,true,()=>new Date(TEST_NOW))(req(x.request));await vi.advanceTimersByTimeAsync(QUOTE_RESPONSE_BUDGET_MS);expect((await result(await pending)).status).toBe('IN_PROGRESS');expect(input?.signal.aborted).toBe(true);}finally{vi.useRealTimers();}});
it('uses a fresh native read and same receipt for simultaneous identical protocol requests',async()=>{const x=setup();const responses=await Promise.all([x.handler(req(x.request)),x.handler(req(x.request))]);const bodies=await Promise.all(responses.map(result));expect(bodies[0].status).toBe('QUOTE_READY');expect(bodies[1]).toEqual(bodies[0]);expect(x.native.loadSnapshot).toHaveBeenCalledTimes(2);});
it('only returns a revised counter amount when exact terms and standing authority still permit it',async()=>{const x=setup(),s=x.snapshot;s.offer.previousPacket=structuredClone(s.offer.packet);s.offer.packet.revision=2;s.offer.packet.priceUsd+=500;x.native.loadSnapshot.mockResolvedValue(s);expect(await result(await x.handler(req(x.request)))).toMatchObject({status:'QUOTE_READY',offer_amount:x.amount+500});});
