import { describe, expect, it } from "vitest";
import { buildCompReportJson, buildCompReportMarkdown } from "./report";
import type { CompsApiResponse } from "./types";

const fixture: CompsApiResponse = {
  subject: {
    address: "123 Main St",
    city: "San Antonio",
    state: "TX",
    zip: "78212",
    sqft: 2000,
    beds: 3,
    baths: 2,
    yearBuilt: 1985,
    propertyType: "Single Family",
    lotSizeAcres: null,
  },
  matchedAddress: "123 Main St, San Antonio, TX 78212",
  addressWasNormalized: false,
  dmReferenceEstimate: null,
  totalSoldCompsFetched: 1,
  outcome: {
    ok: true,
    result: {
      arv: 250000,
      arvPerSqft: 125,
      rangeLow: 240000,
      rangeHigh: 260000,
      confidence: "high",
      confidenceFactors: ["3 qualified comps (thin sample)"],
      tier: { months: 6, radiusMiles: 0.5 },
      usedCompIds: ["comp-1"],
      excludedOutlierIds: [],
      comps: [
        {
          id: "comp-1",
          address: "456 Oak St",
          city: null,
          salePrice: 240000,
          saleDate: "2026-08-01",
          saleType: "sale",
          sqft: 1900,
          beds: 3,
          baths: 2,
          distanceMiles: 0.2,
          propertyType: "Single Family",
          yearBuilt: 1980,
          pricePerSqft: 126.31578947368422,
          monthsAgo: 1.5,
        },
      ],
    },
  },
};

describe("comp report builders", () => {
  it("writes a markdown report with the ARV and comp lines", () => {
    const md = buildCompReportMarkdown(fixture);
    expect(md).toContain("ARV OPINION — 123 Main St, San Antonio, TX 78212");
    expect(md).toContain("ARV: $250,000  ($125/sqft)");
    expect(md).toContain("- 456 Oak St — $240,000");
    expect(md).toContain("Generated by Jarvis Comps");
  });

  it("writes the full response as copyable JSON", () => {
    const parsed = JSON.parse(buildCompReportJson(fixture)) as CompsApiResponse;
    expect(parsed.subject.address).toBe("123 Main St");
    expect(parsed.outcome.ok).toBe(true);
    if (parsed.outcome.ok) {
      expect(parsed.outcome.result.comps).toHaveLength(1);
    }
  });
});
