import type { CompsApiResponse, SubjectSummary } from "./types";

export const usd = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  maximumFractionDigits: 0,
});

export function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export function subjectLine(s: SubjectSummary): string {
  const cityState = [s.city, s.state].filter(Boolean).join(", ");
  return [s.address, cityState, s.zip].filter(Boolean).join(", ");
}

export function buildCompReportMarkdown(data: CompsApiResponse): string {
  const { subject, outcome } = data;
  const lines: string[] = [];
  lines.push(`ARV OPINION — ${data.matchedAddress || subjectLine(subject)}`);
  lines.push("");
  if (outcome.ok) {
    const r = outcome.result;
    lines.push(`ARV: ${usd.format(r.arv)}  (${usd.format(r.arvPerSqft)}/sqft)`);
    lines.push(`Range: ${usd.format(r.rangeLow)} – ${usd.format(r.rangeHigh)}`);
    lines.push(`Confidence: ${r.confidence.toUpperCase()}`);
    lines.push(
      `Basis: median $/sqft of ${r.comps.length} sold comps within ${r.tier.radiusMiles} mi, last ${r.tier.months} months, ±20% sqft, same property type`,
    );
  } else {
    lines.push(`ARV: unavailable — ${outcome.reason}`);
  }
  lines.push("");
  const subj: string[] = [];
  if (subject.beds != null) subj.push(`${subject.beds} bd`);
  if (subject.baths != null) subj.push(`${subject.baths} ba`);
  if (subject.sqft != null) subj.push(`${subject.sqft.toLocaleString()} sqft`);
  if (subject.yearBuilt != null) subj.push(`built ${subject.yearBuilt}`);
  if (subject.propertyType) subj.push(subject.propertyType);
  lines.push(`Subject: ${subj.join(" · ") || "n/a"}`);
  lines.push("");
  const comps = outcome.ok ? outcome.result.comps : outcome.comps;
  if (comps.length) {
    lines.push("COMPS:");
    for (const c of comps) {
      lines.push(
        `- ${c.address} — ${usd.format(c.salePrice)} on ${fmtDate(c.saleDate)} · ${c.sqft.toLocaleString()} sqft · ${c.beds ?? "?"}/${c.baths ?? "?"} · ${c.distanceMiles.toFixed(2)} mi · ${usd.format(Math.round(c.pricePerSqft))}/sqft`,
      );
    }
  }
  lines.push("");
  lines.push("Generated by Jarvis Comps");
  return lines.join("\n");
}

export function buildCompReportJson(data: CompsApiResponse): string {
  return JSON.stringify(data, null, 2);
}
