import {it,expect} from 'vitest';
import {acquisitionPolicyWorkflow,calculateWholesale,exploreAlternatives} from './acquisition-policy';
import {wholesaleFixture} from './estimated-fixtures';
const run=(request:unknown)=>acquisitionPolicyWorkflow({requestJson:JSON.stringify({operation:'calculate_wholesale',request})});
it('owner house formula is exactly 70% of ARV less sqft times selected scope rate',()=>{const out=calculateWholesale(wholesaleFixture());expect(out).toMatchObject({arvUsd:120000,seventyPercentArvUsd:84000,repairRateUsdPerSqft:20,repairsUsd:20000,requestedOfferUsd:64000,additionalDeductionsUsd:0,sellerFacingPacket:null,outboundEnabled:false});expect(out.confidence.label).toBe('PROVIDER_ESTIMATED_ARV');});
it.each(['light','medium','heavy'] as const)('selects explicit %s rate and refuses an unresolved rate',scope=>{const x=wholesaleFixture();x.discovery.repairScope=scope;expect(calculateWholesale(x).repairRateUsdPerSqft).toBe(x.policy.repairRatesUsdPerSqft[scope]);x.policy.repairRatesUsdPerSqft[scope]=null;expect(run(x)).toMatchObject({reason:'REPAIR_RATE_NOT_CONFIGURED'});});
it.each(['land','small_multifamily','commercial_multifamily'] as const)('70%% formula cannot become a universal %s rule',asset=>{const x=wholesaleFixture();x.context.property.asset=asset;expect(run(x)).toMatchObject({reason:'HOUSE_WHOLESALE_ONLY'});});
it.each(['STOP','takeover','wrong-analysis','wrong-property','expired','revoked','rates-reference','rapport','why','repairs','negative','nonfinite','zero-offer','negative-offer','unknown-term'])('formula review path: %s',change=>{const x=wholesaleFixture();if(change==='STOP')x.context.contactDnd=true;if(change==='takeover')x.context.property.humanTakeover='true';if(change==='wrong-analysis')x.analysis.version='v2';if(change==='wrong-property')x.discovery.propertyRecordId='OTHER';if(change==='expired')x.analysis.expiresAt=x.context.now;if(change==='revoked')x.policy.revoked=true;if(change==='rates-reference')x.policy.repairRatesReference=null;if(change==='rapport')x.discovery.rapportReference='';if(change==='why')x.discovery.sellerWhy='';if(change==='repairs')x.discovery.repairDescription='';if(change==='negative')x.policy.repairRatesUsdPerSqft.medium=-1;if(change==='nonfinite')x.subject.sqft=Infinity;if(change==='zero-offer')x.policy.repairRatesUsdPerSqft.medium=84;if(change==='negative-offer')x.policy.repairRatesUsdPerSqft.medium=100;if(change==='unknown-term')Object.assign(x.policy,{assignmentFeeUsd:5000});expect(run(x).status).toBe('NEEDS_REVIEW');});
it('rounds cents deterministically and never invents a confidence percentage',()=>{const x=wholesaleFixture();x.analysis.arvUsd=123456.78;x.subject.sqft=1000.25;x.policy.repairRatesUsdPerSqft.medium=12.34;expect(calculateWholesale(x)).toMatchObject({repairsUsd:12343.09,requestedOfferUsd:74076.66,confidence:{score:null}});});
function situation(){const x=wholesaleFixture();return {context:x.context,sellerFacts:{propertyRecordId:x.context.property.recordId,contactId:x.context.contactId,reportReference:'SYNTHETIC-seller-report',existingMortgage:'unknown',lowEquity:'unknown',ownsFreeAndClear:'unknown',rejectedWholesaleCash:'unknown',willingPartnershipToSell:'unknown'}};}
it.each([['mortgage','SUBJECT_TO_EXPLORATION'],['freeclear','SELLER_FINANCING_MONTHLY_PAYMENTS_EXPLORATION'],['partnership','NOVATION_PARTNERSHIP_EXPLORATION']])('routes %s as exploration without inventing finance terms',(route,expected)=>{const x=situation();if(route==='mortgage'){x.sellerFacts.existingMortgage='yes';x.sellerFacts.lowEquity='yes';}if(route==='freeclear'){x.sellerFacts.ownsFreeAndClear='yes';x.sellerFacts.rejectedWholesaleCash='yes';}if(route==='partnership')x.sellerFacts.willingPartnershipToSell='yes';expect(exploreAlternatives(x)).toMatchObject({candidates:[expected],evidenceClass:'SELLER_REPORTED_UNVERIFIED',loanAssumable:null,lenderConsent:null,equityVerified:false,enforceableTerms:null,financingTerms:null,outboundEnabled:false});});
it('unknown facts select no route; competing routes require selection; contradictory ownership fails',()=>{const x=situation();expect(exploreAlternatives(x).candidates).toEqual([]);x.sellerFacts.existingMortgage='yes';x.sellerFacts.lowEquity='yes';x.sellerFacts.willingPartnershipToSell='yes';expect(exploreAlternatives(x).selectionRequired).toBe(true);x.sellerFacts.ownsFreeAndClear='yes';expect(()=>exploreAlternatives(x)).toThrow('CONFLICTING_SELLER_REPORTS');});
