/** All values and approvals here are SYNTHETIC, not a client buybox or authority. */
import {analysisRequest,type AnalysisRequest} from './contracts';
import {offerRequest} from './offers';
import {stableKey} from './storage';
export function fixture(asset:AnalysisRequest['subject']['asset']='house'):AnalysisRequest {
 const source={provider:'SYNTHETIC-provider',reference:'SYNTHETIC-evidence',retrievedAt:'2026-10-07T08:00:00.000Z',expiresAt:'2026-10-08T08:00:00.000Z',contractVersion:'SYNTHETIC-normalized-v1',synthetic:true};
 const context={locationId:'SesCoVXlNu7qTSBol1gs' as const,now:'2026-10-07T09:00:00.000Z',contactId:'SYNTHETIC-seller',associatedPropertyRecordIds:['SYNTHETIC-A','SYNTHETIC-B'],contactDnd:false,contactTakeover:false,property:{recordId:'SYNTHETIC-A',propertyKey:'SYNTHETIC-key-A',providerPropertyId:'SYNTHETIC-provider-A',propertyVersion:'v1',canonicalAddress:'SYNTHETIC Property A',sourceIdentityReference:'SYNTHETIC-identity',asset,currentAnalysisId:'SYNTHETIC-analysis-A',currentAnalysisVersion:'v1',held:'false' as const,humanTakeover:'false' as const,status:'READY' as const,holdReason:''},analysisRecordId:'SYNTHETIC-analysis-A',analysisKey:'pending',analysisVersion:'v1',expectedPropertyVersion:'v1',expectedCurrentAnalysisId:'SYNTHETIC-analysis-A',expectedCurrentAnalysisVersion:'v1',policyRecordId:'SYNTHETIC-policy',policyVersion:'v1',sourceVersion:'v1',eventId:'SYNTHETIC-event'};
 context.analysisKey=stableKey([context.locationId,context.property.recordId,context.property.providerPropertyId,context.property.propertyVersion,context.analysisVersion,context.policyRecordId,context.policyVersion,context.sourceVersion,context.eventId]);
 const parcel={zoning:'SYNTHETIC-zoning',legalAccess:'SYNTHETIC-access',utilities:'SYNTHETIC-utilities',floodStatus:'SYNTHETIC-flood',boundaryReference:'SYNTHETIC-boundary'};
 return analysisRequest.parse({contract:'jarvis.normalized-analysis.v2',mode:'synthetic_fixture',context,policy:{recordId:context.policyRecordId,version:'v1',approvalReference:'SYNTHETIC-approval',approvedBy:'SYNTHETIC-client',expiresAt:'2026-10-08T08:00:00.000Z',revoked:false,compPriceBasis:'verified_recorded_sales',estimateAcceptanceReference:null,estimatedSaleTypes:[],maxAgeDays:365,maxSourceAgeHours:24,radiusMiles:1,sizeTolerance:0.3,minComps:3,verifiedSaleTypes:['SYNTHETIC-recorded'],houseBasis:'comparable_market_value',maxIncomeSalesDifference:0.2,crosscheckApprovalReference:'SYNTHETIC-crosscheck'},sourceContract:{id:source.contractVersion,verificationReference:'SYNTHETIC-fixture-schema-only'},subject:{providerPropertyId:context.property.providerPropertyId,identityReference:'SYNTHETIC-identity',canonicalAddress:'SYNTHETIC Property A',propertyType:asset,asset,sqft:asset==='land'?null:1000,acres:asset==='land'?2:null,units:asset==='small_multifamily'?3:asset==='commercial_multifamily'?6:null,parcel:asset==='land'?parcel:null,source},comps:asset==='commercial_multifamily'?[]:[110000,120000,130000].map((price,i)=>({id:`SYNTHETIC-comp-${i}`,ordinal:i,displayAddress:`SYNTHETIC Comparable ${i}`,propertyType:asset,salePriceUsd:price,priceKind:'RECORDED',saleDate:'2026-09-01',saleType:'SYNTHETIC-recorded',saleVerified:true,renovatedComparable:true,distanceMiles:0.3,sqft:asset==='land'?null:1000,acres:asset==='land'?2:null,units:asset==='small_multifamily'?3:null,parcel:asset==='land'?parcel:null,source})),facts:['small_multifamily','commercial_multifamily'].includes(asset)?[{name:'grossScheduledAnnualRent',value:20000,unit:'USD/year',source},{name:'vacancyRate',value:0.1,unit:'ratio',source},{name:'annualOperatingExpenses',value:6000,unit:'USD/year',source},{name:'capRate',value:0.1,unit:'ratio',source},{name:'immediateCapitalWork',value:0,unit:'USD',source}]:[]});
}
export function offerFixture(){const x=fixture(),c=x.context;return offerRequest.parse({context:c,packet:{propertyRecordId:c.property.recordId,providerPropertyId:c.property.providerPropertyId,propertyVersion:'v1',recipientId:c.contactId,asset:'house',strategy:'wholesale',priceUsd:65000,terms:{closingDate:'2026-11-01',depositUsd:1000,inspectionDays:10,assignmentAllowed:true,financing:'SYNTHETIC-cash',sellerConcessionsUsd:0},analysisRecordId:c.analysisRecordId,analysisVersion:'v1',policyRecordId:c.policyRecordId,policyVersion:'v1',revision:1},standing:{recordId:c.policyRecordId,version:'v1',approvalReference:'SYNTHETIC-approval',approvedBy:'SYNTHETIC-buyer',expiresAt:x.policy.expiresAt,revoked:false,propertyRecordId:c.property.recordId,recipientId:c.contactId,asset:'house',strategy:'wholesale',minPriceUsd:60000,maxPriceUsd:67000,acceptedValuationBases:['house_verified_market_sales'],estimateAcceptanceReference:null,terms:{closingDate:'2026-11-01',depositUsd:1000,inspectionDays:10,assignmentAllowed:true,financing:'SYNTHETIC-cash',sellerConcessionsUsd:0}},ceiling:{recordId:'SYNTHETIC-ceiling',sourceReference:'SYNTHETIC-approved-economics',approvedBy:'SYNTHETIC-buyer',propertyRecordId:c.property.recordId,analysisRecordId:c.analysisRecordId,analysisVersion:'v1',policyRecordId:c.policyRecordId,policyVersion:'v1',expiresAt:x.policy.expiresAt,valuationBasis:'house_verified_market_sales',ceilingUsd:68000},analysis:{recordId:c.analysisRecordId,propertyRecordId:c.property.recordId,version:'v1',policyRecordId:c.policyRecordId,policyVersion:'v1',completionState:'COMPLETE',status:'READY',expiresAt:x.policy.expiresAt,valuationBasis:'house_verified_market_sales',estimateAcceptanceReference:null,evidenceReadbackReference:'SYNTHETIC-readback'},previousPacket:null});}
export const fixtureLimits={verificationReference:'SYNTHETIC-NOT-A-GHL-LIMIT',maxTextBytes:10000,maxKeyBytes:10000};
