import {it,expect} from 'vitest';
import {offerFixture} from './fixtures';
import {offerKey} from './offers';
import {prepareContract,prepareRevision,reduceContractEvent} from './mason';
function draft(){const offer=offerFixture(),fields={jurisdiction:'SYNTHETIC-TX',templateId:'SYNTHETIC-template',templateVersion:'v1',templateApprovalReference:'SYNTHETIC-client-approved',buyerLegalEntity:'SYNTHETIC-buyer',buyerAuthorityReference:'SYNTHETIC-authority',ownershipReference:'SYNTHETIC-ownership',legalDescription:'SYNTHETIC-description',parcelReference:'SYNTHETIC-parcel',titleEscrow:'SYNTHETIC-title',closingInstructionsReference:'SYNTHETIC-closing',senderId:'SYNTHETIC-sender',deliveryConsentReference:'SYNTHETIC-consent'},signers=[{id:'SYNTHETIC-buyer',role:'buyer',legalName:'SYNTHETIC Buyer',authorityReference:'SYNTHETIC-authority',contactId:'SYNTHETIC-buyer-contact',email:'buyer@example.invalid'},{id:'SYNTHETIC-seller',role:'seller',legalName:'SYNTHETIC Seller',authorityReference:'SYNTHETIC-owner',contactId:offer.packet.recipientId,email:'seller@example.invalid'}];return {offer,fields,signers,draftReadback:{packet:offer.packet,fields:structuredClone(fields),signers:structuredClone(signers)}};}
function lifecycle(){const o=offerFixture();return {context:o.context,currentPacket:o.packet,document:{recordId:'SYNTHETIC-contract',propertyRecordId:o.packet.propertyRecordId,providerPropertyId:o.packet.providerPropertyId,recipientId:o.packet.recipientId,packetKey:offerKey(o.packet),packetRevision:1,documentId:'SYNTHETIC-document',documentRevision:'v1',templateId:'SYNTHETIC-template',templateVersion:'v1',requiredSignerIds:['SYNTHETIC-buyer','SYNTHETIC-seller'],signedSignerIds:[] as string[],state:'DRAFT',conditionsSatisfied:false,sentAt:null as string|null,lastEventAt:null as string|null,events:[] as {id:string;canonicalEvent:string}[]},event:{id:'SYNTHETIC-event-1',locationId:o.context.locationId,propertyRecordId:o.packet.propertyRecordId,documentId:'SYNTHETIC-document',documentRevision:'v1',packetRevision:1,occurredAt:'2026-10-07T08:30:00.000Z',type:'SENT',signerId:null as string|null,completedSignerIds:[] as string[],conditionsSatisfied:false,reconciliationReference:'SYNTHETIC-native-readback'}};}
function sent(){const x=lifecycle(),out=reduceContractEvent(x);x.document=out.document;x.event={...x.event,id:'SYNTHETIC-event-2',occurredAt:'2026-10-07T08:40:00.000Z'};return x;}
it('prepares an exact template and signer snapshot without sending or signing',()=>{const out=prepareContract(draft());expect(out.status).toBe('EXACT_DRAFT_PREPARATION_ONLY');expect(out.sendIntent).toBe(null);expect(out.signatureIntent).toBe(null);});
it.each(['template','terms','signer','authority'])('fails closed for incomplete or changed %s',change=>{const x=draft();if(change==='template')x.draftReadback.fields.templateVersion='v2';if(change==='terms')x.draftReadback.packet={...x.offer.packet,priceUsd:66000};if(change==='signer')x.signers.pop();if(change==='authority')x.fields.buyerAuthorityReference='';expect(()=>prepareContract(x)).toThrow();});
it('deduplicates exact events and refuses event ID reuse with different content',()=>{const x=lifecycle(),out=reduceContractEvent(x);x.document=out.document;expect(reduceContractEvent(x).status).toBe('EXACT_EVENT_REPLAY');x.event.type='VIEWED';expect(()=>reduceContractEvent(x)).toThrow('EVENT_ID_CONFLICT');});
it('a single seller signature never means under contract',()=>{const x=sent();x.event.type='SIGNED';x.event.signerId='SYNTHETIC-seller';const out=reduceContractEvent(x);expect(out.document.state).toBe('PARTIALLY_SIGNED');expect('underContractCandidate' in out&&out.underContractCandidate).toBe(false);});
it('requires every signer and conditions on exact current revision before a completion candidate',()=>{const x=sent();x.event.type='COMPLETED';x.event.completedSignerIds=['SYNTHETIC-seller'];x.event.conditionsSatisfied=true;expect(()=>reduceContractEvent(x)).toThrow('SIGNATURES_OR_CONDITIONS_INCOMPLETE');x.event.completedSignerIds=['SYNTHETIC-buyer','SYNTHETIC-seller'];const out=reduceContractEvent(x);expect(out).toMatchObject({underContractCandidate:true,propertyTransition:null,transitionBlocker:'NATIVE_ATOMIC_TRANSITION_UNVERIFIED',outboundEnabled:false});});
it.each(['document','revision','property','packet'])('ignores old or foreign %s event',change=>{const x=sent();if(change==='document')x.event.documentId='SYNTHETIC-old';if(change==='revision')x.event.documentRevision='v0';if(change==='property')x.event.propertyRecordId='SYNTHETIC-B';if(change==='packet')x.event.packetRevision=2;expect(reduceContractEvent(x).status).toBe('IGNORED_FOREIGN_OR_SUPERSEDED_EVENT');});
it('requires reconciliation of out-of-order events without regressing state',()=>{const x=sent();x.event.occurredAt='2026-10-07T08:00:00.000Z';expect(reduceContractEvent(x).status).toBe('OUT_OF_ORDER_RECONCILIATION_REQUIRED');});
it('contact STOP preserves factual completion but blocks property transition',()=>{const x=sent();x.context.contactDnd=true;x.event.type='COMPLETED';x.event.completedSignerIds=x.document.requiredSignerIds;x.event.conditionsSatisfied=true;const out=reduceContractEvent(x);expect(out.document.state).toBe('COMPLETED');expect(out).toMatchObject({underContractCandidate:false,propertyTransition:null,transitionBlocker:'HELD_OR_STALE_CONTEXT'});});
it.each(['DECLINED','VOIDED','EXPIRED','CANCELLED'])('terminal %s cannot later complete',state=>{const x=sent();x.event.type=state;x.document=reduceContractEvent(x).document;x.event={...x.event,id:'SYNTHETIC-later',type:'COMPLETED',occurredAt:'2026-10-07T08:50:00.000Z',completedSignerIds:x.document.requiredSignerIds,conditionsSatisfied:true};expect(reduceContractEvent(x).status).toBe('TERMINAL_DOCUMENT_PRESERVED');});
it('a sent document must be reconciled closed before a replacement; signed agreement requires amendment',()=>{const x=sent(),replacementPacket={...x.currentPacket,revision:2,priceUsd:66000};expect(()=>prepareRevision({context:x.context,document:x.document,replacementPacket,voidReconciliationReference:null})).toThrow('SENT_DOCUMENT_REQUIRES_VERIFIED_CLOSURE');x.document.state='VOIDED';expect(prepareRevision({context:x.context,document:x.document,replacementPacket,voidReconciliationReference:'SYNTHETIC-void-readback'})).toMatchObject({oldDocumentPreserved:true,oldAuthorizationReusable:false});x.document.state='COMPLETED';expect(()=>prepareRevision({context:x.context,document:x.document,replacementPacket,voidReconciliationReference:'SYNTHETIC-void-readback'})).toThrow('EXECUTED_AGREEMENT_REQUIRES_AMENDMENT');});
it('rejects future events, unexpected signers, contradictory native states and exhausted ledgers',()=>{const x=sent();x.event.occurredAt='2026-10-08T08:00:00.000Z';expect(()=>reduceContractEvent(x)).toThrow('FUTURE_DOCUMENT_EVENT');x.event.occurredAt='2026-10-07T08:40:00.000Z';x.event.type='SIGNED';x.event.signerId='unknown';expect(()=>reduceContractEvent(x)).toThrow('EVENT_SIGNER_INVALID');x.document.state='DRAFT';expect(()=>reduceContractEvent(x)).toThrow('CONTRACT_STATE_INVALID');});
it.each(['legal-description','buyer','signer','sender','authority'])('contract dedup identity changes with the full approved %s snapshot',change=>{const x=draft(),old=prepareContract(x).contractKey;if(change==='legal-description')x.fields.legalDescription='SYNTHETIC-new-description';if(change==='buyer')x.fields.buyerLegalEntity='SYNTHETIC-other-buyer';if(change==='signer')x.signers[1].email='changed@example.invalid';if(change==='sender')x.fields.senderId='SYNTHETIC-other-sender';if(change==='authority')x.fields.buyerAuthorityReference='SYNTHETIC-other-authority';x.draftReadback.fields=structuredClone(x.fields);x.draftReadback.signers=structuredClone(x.signers);expect(prepareContract(x).contractKey).not.toBe(old);expect(prepareContract(x).contractKey).toBe(prepareContract(x).contractKey);});
it.each(['STOP','contact-takeover','property-hold','property-takeover','stale-pointer'])('replacement preparation respects current %s',change=>{const x=lifecycle();if(change==='STOP')x.context.contactDnd=true;if(change==='contact-takeover')x.context.contactTakeover=true;if(change==='property-hold')x.context.property.held='true';if(change==='property-takeover')x.context.property.humanTakeover='true';if(change==='stale-pointer')x.context.property.currentAnalysisVersion='old';expect(()=>prepareRevision({context:x.context,document:x.document,replacementPacket:{...x.currentPacket,revision:2},voidReconciliationReference:null})).toThrow();});
it.each(['provider','asset'])('a self-consistent packet key cannot hide a foreign %s binding',change=>{const x=sent();if(change==='provider')x.currentPacket.providerPropertyId='SYNTHETIC-other-provider';if(change==='asset')x.currentPacket.asset='land';x.document.packetKey=offerKey(x.currentPacket);expect(()=>reduceContractEvent(x)).toThrow('CONTRACT_PROPERTY_OR_PACKET_MISMATCH');});
it.each(['contact','property'])('human takeover preserves completion facts while preventing transition: %s',scope=>{const x=sent();if(scope==='contact')x.context.contactTakeover=true;else x.context.property.humanTakeover='true';x.event.type='COMPLETED';x.event.completedSignerIds=x.document.requiredSignerIds;x.event.conditionsSatisfied=true;expect(reduceContractEvent(x)).toMatchObject({document:{state:'COMPLETED'},underContractCandidate:false,propertyTransition:null});});
