import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {observedWorkflow,reviewObservedPair,bindObservedAnalysis} from './observed-provider';
import {observedReviewExample} from './observed-examples';
import {estimatedFixture} from './estimated-fixtures';
import {fixtureLimits} from './fixtures';
import {stableKey} from './storage';
const run=(x:unknown)=>observedWorkflow({requestJson:JSON.stringify(x)});
it('actual matched pair accepts estimated price class while all unavailable semantics stay unknown',()=>{const out=reviewObservedPair(observedReviewExample().pair);expect(out).toMatchObject({status:'OBSERVED_PAIR_REQUIRES_BINDINGS',priceSelection:{estimatedCount:3,acceptedPriceTypeCount:3,verifiedRecordedSaleCount:0,valuationEligibleCount:0},valuation:null,synthetic:false,outboundEnabled:false,confidence:{score:null,providerUpdatedAt:null,marketCoverage:'UNKNOWN'}});expect(JSON.stringify(out)).not.toContain('"ESTIMATED_PRICE"');expect(out.address).toMatchObject({observations:{property_type:{type:'string',value:'Single Family'},num_units:{value:0},building_condition:{presence:'NULL'},last_sale_price:{value:384400},last_sale_amount:{value:384400}}});});
it('all seven imported sanitized artifacts retain their exact source bytes',()=>{const manifest=JSON.parse(readFileSync('native-deliverables/observed-source/IMPORT-MANIFEST.json','utf8'));expect(manifest.files).toHaveLength(7);for(const item of manifest.files)expect(createHash('sha256').update(readFileSync(`native-deliverables/observed-source/${item.path}`)).digest('hex')).toBe(item.sha256);});
it('no estimate selection is inferred from source labels alone',()=>{const x=observedReviewExample();const out=reviewObservedPair({...x.pair,pricingSelection:null});expect(out).toMatchObject({priceSelection:{acceptedPriceTypeCount:0},valuation:null});});
it('raw distance/currency flags and financial extras cannot fill missing independent bindings',()=>{const x=observedReviewExample();Object.assign(x.pair.compsProjection,{currency:'USD',distanceUnit:'mile',mortgage:'NOT-RETAINED'});expect(JSON.stringify(run(x))).not.toContain('NOT-RETAINED');expect(run({...x,operation:'analyze'})).toMatchObject({status:'NEEDS_REVIEW',reason:'INPUT_SCHEMA_INVALID'});});
/** Deliberately fabricated native/unit/capture/policy bindings to exercise future composition. Not live evidence. */
function simulated(){const x=observedReviewExample(),f=estimatedFixture(),c=f.context;Object.assign(c,{now:'2026-10-07T23:00:00.000Z',contactId:'TEST_ONLY-seller',associatedPropertyRecordIds:['TEST_ONLY-property'],analysisRecordId:'TEST_ONLY-analysis',policyRecordId:'TEST_ONLY-policy',expectedCurrentAnalysisId:'TEST_ONLY-analysis'});Object.assign(c.property,{recordId:'TEST_ONLY-property',providerPropertyId:'prop_125714946',canonicalAddress:'11311 Begonia Rock San Antonio, TX 78245',sourceIdentityReference:'TEST_ONLY-identity',currentAnalysisId:'TEST_ONLY-analysis'});c.analysisKey=stableKey([c.locationId,c.property.recordId,c.property.providerPropertyId,c.property.propertyVersion,c.analysisVersion,c.policyRecordId,c.policyVersion,c.sourceVersion,c.eventId]);Object.assign(f.policy,{recordId:c.policyRecordId,approvalReference:'TEST_ONLY-policy',approvedBy:'TEST_ONLY-owner',estimateAcceptanceReference:x.pair.pricingSelection.acceptanceReference,estimatedSaleTypes:['Estimated Sales Price'],expiresAt:'2026-10-08T23:00:00.000Z'});return {...x,operation:'analyze' as const,bound:{context:c,policy:f.policy,bindings:{classification:{asset:'house',propertyType:'Single Family',reference:'TEST_ONLY-classifier'},currency:{value:'USD',reference:'TEST_ONLY-currency'},livingArea:{value:'sqft',reference:'TEST_ONLY-area'},distance:{value:'mile',reference:'TEST_ONLY-distance'},lot:null,addressCapture:{reference:'TEST_ONLY-address-capture',capturedAt:'2026-10-07T22:40:00.000Z',eligibleUntil:'2026-10-08T22:40:00.000Z'},compsCapture:{reference:'TEST_ONLY-comps-capture',capturedAt:'2026-10-07T22:40:00.000Z',eligibleUntil:'2026-10-08T22:40:00.000Z'}}}};}
it('simulated complete bindings exercise a real-input path with separate estimate prices and raw date provenance',()=>{const x=simulated(),bound=bindObservedAnalysis(x.pair,x.bound);expect(bound.request.subject.units).toBe(null);expect(bound.request.comps.every(c=>c.salePriceUsd===null&&!c.saleVerified&&c.estimatedPriceUsd!>0&&c.acres===null)).toBe(true);const out=run(x);expect(out).toMatchObject({status:'OBSERVED_POLICY_CANDIDATE',basis:'house_provider_estimated_arv',confidence:{recordedSalesVerified:false,score:null},providerMetadata:{updatedAt:null,sourceExpiry:null,marketCoverage:'UNKNOWN'},outboundEnabled:false});expect(JSON.stringify(out)).toContain('2025-11-13T00:00:00.000Z');});
it.each(['currency','distance','area','classification','capture','policy','wrong-native','wrong-sqft','zero-sqft','positive-multiunits','array-category','foreign-id','type-pending','estimated-recorded-label','unknown-price','future-date','capture-before-request','expired','low-size-tolerance','wrong-pointer','held'])('observed composition refuses %s',change=>{const x=simulated();if(change==='currency')Object.assign(x.bound.bindings.currency,{value:null});if(change==='distance')Object.assign(x.bound.bindings.distance,{value:null});if(change==='area')Object.assign(x.bound.bindings.livingArea,{reference:''});if(change==='classification')x.bound.bindings.classification.reference='';if(change==='capture')Object.assign(x.bound.bindings.addressCapture,{capturedAt:null});if(change==='policy')x.bound.policy.estimateAcceptanceReference='OTHER';if(change==='wrong-native')x.bound.context.property.providerPropertyId='prop_1';if(change==='wrong-sqft')x.pair.addressProjection.data[0].living_area_sqft=2600;if(change==='zero-sqft'){x.pair.addressProjection.data[0].living_area_sqft=0;x.pair.compsProjection.data[0].subject.sqft=0;}if(change==='positive-multiunits')x.pair.addressProjection.data[0].num_units=3;if(change==='array-category')Object.assign(x.pair.addressProjection.data[0],{property_type:[9001]});if(change==='foreign-id')x.pair.compsProjection.data[0].comps[0].dm_property_id='prop_125714946';if(change==='type-pending')x.pair.compsProjection.data[0].comps[0].type='pending';if(change==='estimated-recorded-label')x.pair.compsProjection.data[0].comps[0].sale_type='Recorded Sale';if(change==='unknown-price')Object.assign(x.pair.compsProjection.data[0].comps[0],{sale_price:null});if(change==='future-date')x.pair.compsProjection.data[0].comps[0].sale_date='2026-10-07T23:01:00.000Z';if(change==='capture-before-request')x.bound.bindings.compsCapture.capturedAt='2026-10-07T21:00:00.000Z';if(change==='expired')x.bound.policy.expiresAt=x.bound.context.now;if(change==='low-size-tolerance')x.bound.policy.sizeTolerance=0.01;if(change==='wrong-pointer')x.bound.context.property.currentAnalysisVersion='v2';if(change==='held')x.bound.context.contactDnd=true;expect(run(x).status).toBe('NEEDS_REVIEW');});
it('observed native preparation persists estimate facts only and rechecks a newly received STOP',()=>{const x=simulated(),prepare={...x,operation:'prepare',fieldLimits:fixtureLimits};const plan=run(prepare);expect(plan).toHaveProperty('evidence');if(!('analysis' in plan))throw Error('Expected plan');expect(plan.evidence.filter(e=>e.properties.row_kind==='SALE').every(e=>!Object.hasOwn(e.properties,'sale_price_usd'))).toBe(true);const c=x.bound.context,read={contact:{contactId:c.contactId,associatedPropertyRecordIds:c.associatedPropertyRecordIds,contactDnd:false,contactTakeover:false},property:c.property,policy:x.bound.policy,analysis:plan.analysis,evidence:plan.evidence.map((e,i)=>({...e,recordId:`TEST_ONLY-evidence-${i}`})),allPagesRead:true};expect(run({...prepare,operation:'reconcile',readback:read})).toMatchObject({status:'EXACT_READBACK_MATCH',pointerUpdate:null});read.contact.contactDnd=true;expect(run({...prepare,operation:'reconcile',readback:read})).toMatchObject({reason:'HELD_OR_NOT_READY'});});
