import {it,expect} from 'vitest';
import {mapDocumentedProperty,propertyWorkflow} from './property-adapter';
import {propertyFixture} from './property-fixtures';
const run=(request:unknown)=>propertyWorkflow({requestJson:JSON.stringify(request)});
function address(){const x=propertyFixture();if(x.operation!=='address')throw Error('fixture');return x;}
function get(){const x=propertyFixture('get_property');if(x.operation!=='get_property')throw Error('fixture');return x;}
it.each(['address','get_property'] as const)('maps documented %s projection without claiming value or verified sale',operation=>{const out=mapDocumentedProperty(propertyFixture(operation));expect(out).toMatchObject({saleVerified:false,renovatedComparable:false,assetClassification:null,valuation:null,comps:null,outboundEnabled:false,synthetic:true});expect(out.observations.find(f=>f.field==='living_area_sqft')).toMatchObject({value:1200,unit:'sqft',path:operation==='address'?'$.data[0].living_area_sqft':'$.data.living_area_sqft'});});
it('keeps endpoint-specific last sale, estimate and listing amounts separate',()=>{const a=mapDocumentedProperty(address()),g=mapDocumentedProperty(get());expect(a.observations.find(f=>f.field==='last_sale_price')?.value).toBe(150000);expect(g.observations.find(f=>f.field==='last_sale_amount')?.value).toBe(150000);expect(g.observations.find(f=>f.field==='last_sale_price')).toBeUndefined();expect(g.observations.find(f=>f.field==='estimated_value')).toMatchObject({value:190000,meaning:'PROVIDER_ESTIMATE'});expect(g.observations.find(f=>f.field==='mls_current_listing_price')).toMatchObject({value:205000,meaning:'LIST_PRICE'});expect(g.blockers).toContain('CATALOG_LAST_SALE_PRICE_VS_GET_LAST_SALE_AMOUNT');});
it('does not alias conflicting documented names across endpoints',()=>{const g=get();Object.assign(g.responseProjection.data,{last_sale_price:150000});expect(run(g)).toMatchObject({reason:'INPUT_SCHEMA_INVALID'});const a=address();Object.assign(a.responseProjection.data[0],{last_sale_amount:150000});expect(run(a)).toMatchObject({reason:'INPUT_SCHEMA_INVALID'});});
it('a catalog selector does not imply GET will return an identically named sale field',()=>{const g=get();g.request.query.fields+=',last_sale_price';expect(mapDocumentedProperty(g).blockers).toContain('REQUESTED_FIELD_MISSING');});
it('unknown, null and actual numeric zero remain distinguishable',()=>{const g=get();delete g.responseProjection.data.living_area_sqft;g.responseProjection.data.lot_size_acres=null;const out=mapDocumentedProperty(g);expect(out.observations.find(f=>f.field==='living_area_sqft')).toMatchObject({presence:'MISSING',value:null});expect(out.observations.find(f=>f.field==='lot_size_acres')).toMatchObject({presence:'NULL',value:null,unit:'acre'});expect(out.observations.find(f=>f.field==='num_commercial_units')).toMatchObject({presence:'VALUE',value:0});expect(out.blockers).toContain('REQUESTED_FIELD_MISSING');});
it.each(['1200','',false,[],{},-1])('rejects malformed physical number %j without coercion',value=>{const x=get();Object.assign(x.responseProjection.data,{living_area_sqft:value});expect(run(x)).toMatchObject({reason:'INPUT_SCHEMA_INVALID'});});
it.each(['Single Family','1',['1'],[1,1],[1.5]])('category value %j must be unique numeric option IDs',value=>{const x=get();Object.assign(x.responseProjection.data,{property_type:value});expect(run(x)).toMatchObject({reason:'INPUT_SCHEMA_INVALID'});});
it('category labels come only from matching typed metadata, never a built-in dictionary',()=>{const x=get();expect(mapDocumentedProperty(x).observations.find(f=>f.field==='property_type')?.labels).toEqual(['SYNTHETIC property category']);x.metadata=null;const out=mapDocumentedProperty(x);expect(out.observations.find(f=>f.field==='property_type')?.labels).toBe(null);expect(out.blockers).toContain('CATEGORY_METADATA_REQUIRED');});
it('string metadata option ID is not silently converted to a numeric response ID',()=>{const x=get();x.metadata!.filters[0].options[0].option_id='9001';expect(mapDocumentedProperty(x).blockers).toContain('CATEGORY_OPTION_UNRESOLVED');});
it.each(['expired','duplicate-filter','duplicate-option'])('refuses ambiguous or stale metadata: %s',change=>{const x=get();if(change==='expired')x.metadata!.expiresAt=x.now;if(change==='duplicate-filter')x.metadata!.filters[1]=x.metadata!.filters[0];if(change==='duplicate-option')x.metadata!.filters[0].options.push(x.metadata!.filters[0].options[0]);expect(run(x).status).toBe('NEEDS_REVIEW');});
it('preserves different unit counts and area units without inferring an asset or NOI',()=>{const x=get();x.responseProjection.data.num_units=8;x.responseProjection.data.num_commercial_units=2;const out=mapDocumentedProperty(x);expect(out.observations.find(f=>f.field==='num_units')?.value).toBe(8);expect(out.observations.find(f=>f.field==='num_commercial_units')?.value).toBe(2);expect(out.observations.find(f=>f.field==='lot_size_sqft')?.unit).toBe('sqft');expect(out.observations.find(f=>f.field==='lot_size_acres')?.unit).toBe('acre');expect(out.assetClassification).toBe(null);expect(JSON.stringify(out)).not.toContain('noiUsd');});
it.each(['array-for-get','object-for-address','wrong-id','conflated-id','bad-total','wrong-echo','warning','unmatched','contacts'])('refuses endpoint/provenance mismatch: %s',change=>{const g=get(),a=address();let x:unknown=g;if(change==='array-for-get')x={...g,responseProjection:{data:[g.responseProjection.data]}};if(change==='object-for-address')x={...a,responseProjection:{data:a.responseProjection.data[0],totals:a.responseProjection.totals}};if(change==='wrong-id')g.request.id='SYNTHETIC-other';if(change==='conflated-id')g.nativePropertyRecordId=g.request.id;if(change==='bad-total'){a.responseProjection.totals.matched=0;x=a;}if(change==='wrong-echo'){a.responseProjection.data[0].input.full_address='SYNTHETIC-other';x=a;}if(change==='warning'){Object.assign(a.responseProjection.data[0],{match_warning:{code:'rewritten',message:'SYNTHETIC-warning'}});x=a;}if(change==='unmatched'){x={...a,responseProjection:{data:[{input:a.request.data[0],matched:false,match_failure:{code:'not_found',reason:'SYNTHETIC'}}],totals:{submitted:1,matched:0,unmatched:1}}};}if(change==='contacts')Object.assign(g.responseProjection.data,{contacts:[{owner:'NEVER-ECHO'}]});const out=run(x);expect(out.status).toBe('NEEDS_REVIEW');expect(JSON.stringify(out)).not.toContain('NEVER-ECHO');});
it.each(['2026-02-30','2026-09-01T00:00:00Z','09/01/2026'])('refuses undocumented or invalid sale date %s',saleDate=>{const g=get();Object.assign(g.responseProjection.data,{last_sale_date:saleDate});expect(run(g).status).toBe('NEEDS_REVIEW');});
it('real property binding stays unavailable and no input can enable comps',()=>{const x=get();x.mode='real';expect(run(x)).toMatchObject({reason:'LIVE_PROPERTY_BINDING_UNVERIFIED'});expect(run({...x,providerMappingAvailable:true})).toMatchObject({reason:'INPUT_SCHEMA_INVALID'});});
