import {it,expect} from 'vitest';
import {fixture,fixtureLimits} from './fixtures';
import {prepareStorage,reconcileStorage,classifyReplay,type Stored} from './storage';
function readback(){const input=fixture(),plan=prepareStorage(input,fixtureLimits);return {input,plan,read:{contact:{contactId:input.context.contactId,associatedPropertyRecordIds:input.context.associatedPropertyRecordIds,contactDnd:false,contactTakeover:false},allPagesRead:true,analysis:structuredClone(plan.analysis) as Stored,evidence:plan.evidence.map((r,i)=>({...structuredClone(r),recordId:`SYNTHETIC-evidence-${i}`})),property:input.context.property,policy:input.policy}};}
it('maps only verified fields and verifies exact full readback before completion intent',()=>{const {input,plan,read}=readback();const out=reconcileStorage(input,fixtureLimits,read);expect(out.status).toBe('EXACT_READBACK_MATCH');expect(plan.analysis.properties.completion_state).toBe('INCOMPLETE');expect(out.completionIntent?.properties.completion_state).toBe('COMPLETE');expect(out.pointerUpdate).toBe(null);expect(out.outboundEnabled).toBe(false);});
it('idempotent same-key same-content retries match; differences conflict',()=>{const {plan,read}=readback();expect(classifyReplay(plan.evidence[0],read.evidence[0])).toBe('EXACT_REPLAY');read.evidence[0].properties.fact_value_text='truncated';expect(classifyReplay(plan.evidence[0],read.evidence[0])).toBe('CONFLICT');});
it.each(['missing','extra','duplicate','wrong-parent','wrong-analysis','changed-policy','changed-property','partial-page'])('refuses incomplete/conflicting readback: %s',change=>{const {input,read}=readback();if(change==='missing')read.evidence.pop();if(change==='extra')read.evidence.push({...read.evidence[0],recordId:'extra'});if(change==='duplicate')read.evidence[1]=read.evidence[0];if(change==='wrong-parent')read.evidence[0].parentRecordId='SYNTHETIC-other';if(change==='wrong-analysis')read.analysis.recordId='SYNTHETIC-other';if(change==='changed-policy')read.policy={...read.policy,revoked:true};if(change==='changed-property')read.property={...read.property,propertyVersion:'v2'};if(change==='partial-page')read.allPagesRead=false;expect(()=>reconcileStorage(input,fixtureLimits,read)).toThrow();});
it('reordered pages still reconcile by unique identity',()=>{const {input,read}=readback();read.evidence.reverse();expect(reconcileStorage(input,fixtureLimits,read).status).toBe('EXACT_READBACK_MATCH');});
it('rejects caller-chosen analysis key and unknown text capacity',()=>{const input=fixture();input.context.analysisKey='wrong';expect(()=>prepareStorage(input,fixtureLimits)).toThrow('ANALYSIS_KEY_MISMATCH');expect(()=>prepareStorage(fixture(),{})).toThrow();expect(()=>prepareStorage(fixture(),{...fixtureLimits,maxTextBytes:2})).toThrow('NATIVE_TEXT_CAP_EXCEEDED');});
it('does not write a price number for estimated or malformed rejected evidence',()=>{const input=fixture();input.comps.push({...input.comps[0],id:'SYNTHETIC-estimate',ordinal:3,priceKind:'ESTIMATED'});input.comps.push({...input.comps[0],id:'SYNTHETIC-malformed',ordinal:4,salePriceUsd:'$123456'});const plan=prepareStorage(input,fixtureLimits);const rejected=plan.evidence.filter(e=>e.properties.row_kind==='SALE'&&e.properties.selection==='REJECTED');expect(rejected).toHaveLength(2);expect(rejected.every(r=>!Object.hasOwn(r.properties,'sale_price_usd'))).toBe(true);});
it('a new analysis can stage while the old pointer remains unchanged',()=>{const input=fixture();input.context.analysisRecordId='SYNTHETIC-analysis-new';expect(prepareStorage(input,fixtureLimits).pointerUpdate).toBe(null);});
it('allocates a pending record without inventing a native record ID or advancing the pointer',async()=>{const {allocateAnalysis}=await import('./storage');const x=fixture();const {analysisRecordId,analysisKey,...context}=x.context;expect(analysisRecordId).toBeTruthy();expect(analysisKey).toBeTruthy();const out=allocateAnalysis({context,policy:x.policy,mode:'synthetic_fixture'},fixtureLimits);expect(out.analysis.recordId).toBe(null);expect(out.analysis.uniqueKey).toBe(x.context.analysisKey);expect(out.analysis.properties.completion_state).toBe('INCOMPLETE');expect(out.pointerUpdate).toBe(null);});
it('native-generated record IDs are permitted for synthetic record roundtrip while provider identity stays synthetic',()=>{const x=fixture();x.context.property.recordId='native-record-123';x.context.associatedPropertyRecordIds=['native-record-123'];x.context.analysisRecordId='native-analysis-123';x.context.analysisKey=x.context.analysisKey.replace('11:SYNTHETIC-A','17:native-record-123');expect(()=>prepareStorage(x,fixtureLimits)).not.toThrow();});
it('a completed analysis replay verifies all evidence and emits no downgrade or second completion write',()=>{const {input,read}=readback();const first=reconcileStorage(input,fixtureLimits,read);read.analysis=first.completionIntent as Stored;expect(reconcileStorage(input,fixtureLimits,read)).toMatchObject({status:'EXACT_COMPLETE_REPLAY',completionIntent:null,pointerUpdate:null});read.evidence[0].properties.fact_value_text='changed';expect(()=>reconcileStorage(input,fixtureLimits,read)).toThrow('EVIDENCE_READBACK_CONFLICT');});
it('first analysis can allocate with an explicitly empty current pointer pair, never a half pointer',async()=>{const {allocateAnalysis}=await import('./storage');const x=fixture();x.context.property.currentAnalysisId='';x.context.property.currentAnalysisVersion='';x.context.expectedCurrentAnalysisId='';x.context.expectedCurrentAnalysisVersion='';const {analysisRecordId,analysisKey,...context}=x.context;expect(analysisRecordId&&analysisKey).toBeTruthy();expect(allocateAnalysis({context,policy:x.policy,mode:'synthetic_fixture'},fixtureLimits).status).toBe('ALLOCATE_PENDING_ONLY');context.property.currentAnalysisVersion='v1';expect(()=>allocateAnalysis({context,policy:x.policy,mode:'synthetic_fixture'},fixtureLimits)).toThrow('INCOMPLETE_ANALYSIS_POINTER');});
it.each(['STOP','takeover','association-removed','foreign-contact'])('fresh contact readback blocks completion on %s',change=>{const {input,read}=readback();if(change==='STOP')read.contact.contactDnd=true;if(change==='takeover')read.contact.contactTakeover=true;if(change==='association-removed')read.contact.associatedPropertyRecordIds=['SYNTHETIC-B'];if(change==='foreign-contact')read.contact.contactId='SYNTHETIC-other-seller';expect(()=>reconcileStorage(input,fixtureLimits,read)).toThrow();});
it('rejects readback that omits the final contact-wide hold check',()=>{const {input,read}=readback();const {contact,...withoutContact}=read;expect(contact).toBeTruthy();expect(()=>reconcileStorage(input,fixtureLimits,withoutContact)).toThrow();});
it('does not persist a recorded-price claim when sale type or verification contradicts it',()=>{const x=fixture();x.comps.push({...x.comps[0],id:'SYNTHETIC-unverified',ordinal:3,saleVerified:false});x.comps.push({...x.comps[0],id:'SYNTHETIC-estimated-type',ordinal:4,saleType:'Estimated Sales Price'});const rows=prepareStorage(x,fixtureLimits).evidence.filter(e=>e.properties.row_kind==='SALE'&&e.properties.selection==='REJECTED');expect(rows).toHaveLength(2);expect(rows.every(r=>!Object.hasOwn(r.properties,'sale_price_usd'))).toBe(true);});
it('real allocation remains PENDING with native identity supplied independently and rejects fixture mixing',async()=>{const {allocateAnalysis}=await import('./storage');const x=fixture();const {analysisRecordId,analysisKey,...context}=x.context;expect(analysisRecordId&&analysisKey).toBeTruthy();expect(()=>allocateAnalysis({context,policy:x.policy,mode:'real'},fixtureLimits)).toThrow('SYNTHETIC_REAL_MIX');context.property.recordId='TEST_ONLY-native-property';context.associatedPropertyRecordIds=[context.property.recordId];context.property.providerPropertyId='prop_900000001';context.contactId='TEST_ONLY-contact';context.policyRecordId='TEST_ONLY-policy';x.policy.recordId=context.policyRecordId;x.policy.approvalReference='TEST_ONLY-native-policy-reference';const out=allocateAnalysis({context,policy:x.policy,mode:'real'},fixtureLimits);expect(out).toMatchObject({status:'ALLOCATE_PENDING_ONLY',mode:'real',analysis:{recordId:null,properties:{status:'PENDING',completion_state:'INCOMPLETE'}},pointerUpdate:null,outboundEnabled:false});});
