import {it,expect,vi,afterEach} from 'vitest';
import {LOCATION} from '../../../../lib/native/contracts';
import {fixture} from '../../../../lib/ghl-native-quote.test-fixtures';
import {TEST_NOW} from '../../../../lib/native-quote.test-fixtures';
import type {GhlRequest} from '../../../../lib/ghl-native-quote';
const db=vi.hoisted(()=>({$queryRawUnsafe:vi.fn()}));
vi.mock('../../../../lib/db',()=>({db}));
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.unstubAllEnvs();vi.resetModules();db.$queryRawUnsafe.mockReset();});
it('the actual POST route is disabled by default and does not touch the database',async()=>{vi.stubEnv('JARVIS_NATIVE_QUOTE_ENABLED','false');const {POST,runtime}=await import('./route');expect(runtime).toBe('nodejs');const response=await POST(new Request('https://example.invalid',{method:'POST'}));expect(response.status).toBe(503);expect((await response.json()).status).toBe('UNAVAILABLE');expect(db.$queryRawUnsafe).not.toHaveBeenCalled();});
it('enabling the flag cannot bypass the missing native runtime',async()=>{vi.stubEnv('JARVIS_NATIVE_QUOTE_ENABLED','true');db.$queryRawUnsafe.mockResolvedValue([{agency:'TEST_ONLY-agency',location:LOCATION,actor:'TEST_ONLY-actor'}]);const {POST}=await import('./route');const response=await POST(new Request('https://example.invalid',{method:'POST',headers:{authorization:'Bearer TEST_ONLY-token-not-a-real-credential','content-type':'application/json'},body:JSON.stringify({request_id:'TEST_ONLY-request',call_id:'TEST_ONLY-call',contact_id:'TEST_ONLY-seller',property_record_id:'TEST_ONLY-property',analysis_id:'TEST_ONLY-analysis',analysis_version:'v1'})}));expect(response.status).toBe(503);expect(await response.json()).not.toHaveProperty('offer_amount');expect(db.$queryRawUnsafe).toHaveBeenCalledTimes(1);});

it('the old acquisition enable flag cannot enable the quote route',async()=>{vi.stubEnv('JARVIS_ACQUISITIONS_ENABLED','true');vi.stubEnv('JARVIS_NATIVE_QUOTE_ENABLED','false');const {POST}=await import('./route');expect((await POST(new Request('https://example.invalid',{method:'POST'}))).status).toBe(503);expect(db.$queryRawUnsafe).not.toHaveBeenCalled();});
function configuredRoute(){
 const x=fixture(true);vi.useFakeTimers();vi.setSystemTime(new Date(TEST_NOW));
 vi.stubEnv('JARVIS_NATIVE_QUOTE_ENABLED','true');vi.stubEnv('JARVIS_ACQUISITIONS_ENABLED','false');vi.stubEnv('JARVIS_NATIVE_QUOTE_BINDINGS_JSON',JSON.stringify(x.bindings));vi.stubEnv('JARVIS_GHL_PRIVATE_INTEGRATION_TOKEN','TEST_ONLY-outbound-private-integration');
 const outbound=vi.fn<typeof fetch>(async(url,init)=>{const u=new URL(String(url));expect(u.origin).toBe('https://services.leadconnectorhq.com');expect(init?.redirect).toBe('manual');expect(init?.cache).toBe('no-store');const headers=new Headers(init?.headers);expect(headers.get('authorization')).toBe('Bearer TEST_ONLY-outbound-private-integration');expect(headers.get('version')).toBe('v3');let query:GhlRequest['query'];if(u.pathname.startsWith('/associations/'))query={locationId:u.searchParams.get('locationId')!,skip:Number(u.searchParams.get('skip')),limit:Number(u.searchParams.get('limit')),associationIds:u.searchParams.getAll('associationIds')};const response=await x.transport({method:init!.method as 'GET'|'POST',path:u.pathname,query,body:init?.body?JSON.parse(String(init.body)):undefined,version:headers.get('version')!,signal:init!.signal!});return Response.json(response.body,{status:response.status});});
 vi.stubGlobal('fetch',outbound);db.$queryRawUnsafe.mockResolvedValue([x.principal]);return {x,outbound};
}
it('actual configured POST composes the real secure transport, adapter and deterministic quote, then durably replays',async()=>{const {x,outbound}=configuredRoute();const {POST,maxDuration}=await import('./route');expect(maxDuration).toBe(15);const legacyComps=await import('../comps/route'),legacyProposals=await import('../proposals/route');expect((await legacyComps.POST(x.request())).status).toBe(503);expect((await legacyProposals.POST(x.request())).status).toBe(503);expect(outbound).not.toHaveBeenCalled();const one=await (await POST(x.request())).json(),two=await (await POST(x.request())).json();expect(one).toMatchObject({status:'QUOTE_READY',offer_amount:x.amount,quote_id:'TEST_ONLY-quote-1'});expect(two).toEqual(one);expect(x.creations()).toBe(1);expect(outbound).toHaveBeenCalled();expect(process.env.JARVIS_ACQUISITIONS_ENABLED).toBe('false');});
it('configured POST sends no GHL traffic when machine authorization fails',async()=>{const {x,outbound}=configuredRoute();db.$queryRawUnsafe.mockResolvedValue([]);const {POST}=await import('./route');expect((await POST(x.request())).status).toBe(401);expect(outbound).not.toHaveBeenCalled();});
it('configured POST returns no offer when the native API denies access',async()=>{const {x}=configuredRoute();x.setIntercept(()=>({status:403,body:{private:'TEST_ONLY-never-return'}}));const {POST}=await import('./route');const r=await POST(x.request()),body=await r.json();expect(r.status).toBe(503);expect(body.status).toBe('UNAVAILABLE');expect(body).not.toHaveProperty('offer_amount');expect(JSON.stringify(body)).not.toContain('TEST_ONLY-never-return');expect(x.creations()).toBe(0);});
