/** Local-only JSON contracts. No production defaults or live payloads. */
import {mkdir,writeFile} from 'node:fs/promises';
import {z} from 'zod';
import {quoteRequest,sellerQuoteResponse,quoteSnapshot,quoteReceipt} from '../src/lib/native-quote-contract';
import {ghlQuoteBindings,nativeQuoteContextEnvelope,nativeQuotePolicyEnvelope,nativeQuoteOfferEnvelope} from '../src/lib/ghl-native-quote';
import inventory from '../native-deliverables/native-installed-schema.json';
async function main(){
 await mkdir('native-deliverables/http',{recursive:true});
 for(const [name,schema] of Object.entries({request:quoteRequest,response:sellerQuoteResponse,snapshot:quoteSnapshot,receipt:quoteReceipt,'ghl-bindings':ghlQuoteBindings,'native-context':nativeQuoteContextEnvelope,'native-policy':nativeQuotePolicyEnvelope,'native-offer':nativeQuoteOfferEnvelope}))await writeFile(`native-deliverables/http/${name}.schema.json`,JSON.stringify(z.toJSONSchema(schema),null,2)+'\n');
 await writeFile('native-deliverables/admin-config/comp-policy-proposal.json',JSON.stringify({status:'PROPOSED_NOT_ADOPTED',active:false,radiusMiles:1,maxAgeDays:365,sizeTolerance:0.3,minComps:3,maxSourceAgeHours:24,approvalReference:null,approvedBy:null,policyRecordId:null,note:'Administrative proposal only. No runtime default. Native adopted policy and exact approval evidence are required.'},null,2)+'\n');
 await writeFile('native-deliverables/http/installed-binding-review.json',JSON.stringify({status:'MAPPING_CANDIDATE_NOT_RUNTIME_CONFIG',active:false,locationId:inventory.locationId,storageMode:'installed_fields',context:{schemaKey:'custom_objects.jarvis_acq_lifecycle_events',keyField:'event_key',payloadField:'canonical_event',eventType:'QUOTE_CONTEXT_SNAPSHOT'},quote:{schemaKey:'custom_objects.jarvis_acq_lifecycle_events',keyField:'event_key',payloadField:'canonical_event',eventType:'QUOTE_DECISION_RECORDED',claimedLocationField:'event_location_id',uniqueRequestKeyVerified:false,maxPayloadBytes:null},policy:{schemaKey:'custom_objects.jarvis_acq_policies',configurationScope:null,repairDefaultsOnlyRecordId:'6ac6d94e18c960322a93986c',repairDefaultsAreOfferAuthority:false},offer:{schemaKey:'custom_objects.jarvis_acq_offers',approvedOfferStates:[]},ceiling:{schemaKey:'custom_objects.jarvis_acq_sourced_ceilings'},uiAssociationCandidates:inventory.associations.filter(a=>['Seller','ACQ Property Analysis','ACQ Analysis Evidence'].includes(a.label)),unresolved:['authorized server transport and exact API version','API association definition ID translation and relation envelope','Contact global/voice DND and takeover mapping','API unique conflict/read-after-write behavior and capacities','restricted native writers and searchable keys','protected native context event with structured supplements','adopted full policy and exact offer/ceiling records'],scopeStringsFromBrowserProposal:['objects/schema.readonly','objects/record.readonly','objects/record.write','associations.readonly','associations/relation.readonly','associations/relation.write'],credentialsIncluded:false},null,2)+'\n');
 console.log('Exported eight HTTP/native-runtime schemas and inactive comp-policy proposal. No live configuration supplied.');
}
void main().catch(()=>{console.error('Quote contract export failed.');process.exitCode=1;});
